name: 'tpch_local'
version: '1.0.0'
profile: 'tpch_local'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  tpch_local:
    +materialized: table
    +schema: marts
    staging:
      +materialized: view
    intermediate:
      +materialized: view
